### ISSUE TITLE
Should errors getting token print error_description as well?

### ISSUE THREAD

**Issue by sbwp** [feross/reddit#3]
Currently when an error occurs while getting a token, it prints `body.error`. Should it also print `body.error_description`? For example, I got this error because I forgot to switch the toggle to "script": `{"error_description":"Only script apps may use password auth","error":"unauthorized_client"}`. Because it only printed `body.error`, I spent several minutes trying to figure out why I was getting "unauthorized_client", when I would have immediately figured it out with "Only script apps may use password auth", which I didn't find until I modified the log in this package to print the whole error object. I'm not sure if all types of errors provide a description, though. Thoughts?

**Comment by feross** [comment]
Fixed and released as 1.2.1
