### ISSUE TITLE
Return response headers or obey rate limit

### ISSUE THREAD

**Issue by Gjum** [feross/reddit#4]
I'm interested in properly handling the X-Ratelimit-Used, X-Ratelimit-Remaining, and X-Ratelimit-Reset headers.

I'm not sure what would be the best way to expose them in the returned object.

**Comment by feross** [comment]
Perhaps we can include a `.response` property on the returned object which includes the full Node.js response object?

Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!
